Introduce OAuth2 caching
SAP/cloud-sdk-java pull request #106
Opened 2023-10-25 09:35 UTC by cschubertcs

2023-10-26 08:38 UTC, cschubertcs commented
Still pending some documentation in form of javadoc as "ADR".

2023-10-27 08:07 UTC, cschubertcs commented
Can now be fully reviewed

2023-10-30 15:17 UTC, CharlesDuboisSAP commented on cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OnPremTest.java
> +{
This tests separation only from `/oauth/token` and not `authorizeEndpoint` and `jwksUri`.

2023-10-30 15:17 UTC, CharlesDuboisSAP commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceImpl.java
> +    }
A new `OAuth2ServiceImpl` is still created for every destination. Couldn't the cache be one level higher at `OAuth2ServiceBindingDestinationLoader.createHeaderProvider`?

2023-10-30 19:53 UTC, cschubertcs commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceImpl.java
> +    }
Hm, I think there would not be a lot of benefit of caching the `OAuth2ServiceImpl`, as there is not a lot of state connected to it or created (besides the now cached `XsuaaTokenFlows`). The only thing I would spontaneously see would be a minor memory efficiency win.
Also, the `OAuth2ServiceImpl` gets used by `OAuth2DestinationBuilder` and `OAuth2ServiceBindingDestinationLoader`, meaning we would need to cache it in both of those classes.

2023-10-30 19:56 UTC, cschubertcs commented on cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OnPremTest.java
> +{
Hm, true, but I don't have a spontaneous good idea on how to test those, as this is used under the hood by the XsuaaTokenFlows, not by us, to retrieve the actual token we mock in here.
The most important part is actually the `baseUri`, and that is the same for all three of them.

I will have a look tomorrow to see some reasonable way to check those as well.

2023-11-01 13:11 UTC, cschubertcs commented on cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OnPremTest.java
> +{
I don't see any way to test this:
- The `Endpoints` class itself is simple implementation of the `OAuth2ServiceEndpointsProvider` interface
- The evaluation of the interface methods happens inside the security library. The tests only mock the usual OAuth flow, which happens to use the `/oauth/token` endpoint.
- The only parameter of `Endpoints` is the `baseUri`, which we could use alternatively as a key. We just decided against it, in case that we change anything in the implementation of the `Endpoints` class.

All in all I don't see a way and also no benefit in testing these other properties.

2023-11-01 17:16 UTC, newtork commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceImpl.java
> +        Caffeine.newBuilder().expireAfterAccess(1, TimeUnit.HOURS).build();
(Major)

<details>
<summary>I think we should leverage the caching capabilities from XSUAA security library</summary>

![image](https://github.com/SAP/cloud-sdk-java/assets/22489773/bf23b6ca-6312-4cff-8764-857bd0e424f7)

</details>

Instead of cached lookup:
```
String, OAuth2ServiceEndpointsProvider, ClientIdentity -> XsuaaTokenFlows
```
You could just cache-lookup:
```
ClientIdentity -> DefaultOAuth2TokenService
```

The rest should work automatically, As far as I understood, `XsuaaTokenFlows` can be instantiated with every call, it's immutable and low-footprint.

2023-11-03 07:37 UTC, cschubertcs commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceImpl.java
> +        Caffeine.newBuilder().expireAfterAccess(1, TimeUnit.HOURS).build();
Hm, that kind of makes sense, I will try it out!

We are currently already leveraging the response cache in the `AbstractOAuth2TokenService`, but the way you propose looks much more manageable and less error prone.

2023-11-03 09:56 UTC, Johannes-Schneider commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceImpl.java
> +     * <li>{@code ClientIdentity}, to separate by the credentials used against the OAuth2 service.</li>
I'm wondering:
Since we are no longer using the actual token endpoint URI for our cache key, chances are (even if almost zero) that  we do have two different token services that do use the same `ClientIdentity` (i.e. same `clientid`, `clientsecret).

As far as I could see, this shouldn't be an issue as the XSUAA lib already uses the actual token endpoint uri for their internal cache.
Nevertheless, I think it would be nice to be rather sure by introducing a corresponding unit test.
That way, we will also notice in case the XSUAA lib ever decides to change their internal implementation for whatever reason.

2023-11-03 10:39 UTC, cschubertcs commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceImpl.java
> +     * <li>{@code ClientIdentity}, to separate by the credentials used against the OAuth2 service.</li>
Makes sense, test added!

2023-11-03 12:21 UTC, newtork requested changes
Let me check whether we can move "behalf" evaluation from lazy to eager.

2023-11-03 13:21 UTC, newtork commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceImpl.java
> +    XsuaaTokenFlows createTokenFlow( final String zoneId )
(Major)

To avoid future confusion, this method does not "create a token flow" but it "creates a token flow factory" 😁 

Maybe...
```suggestion
    XsuaaTokenFlows getTokenFlows( final String zoneId )
```

2023-11-03 15:52 UTC, newtork approved these changes

2023-11-03 16:13 UTC, merged