feat: Add error handling for incorrect destination configuration in HttpClientWrapper
SAP/cloud-sdk-java pull request #112
Opened 2023-11-01 15:45 UTC by CharlesDuboisSAP

# Pull Request Description

This PR addresses the backlog item [#320](https://github.com/SAP/cloud-sdk-java-backlog/issues/320) and introduces a new feature to the `HttpClientWrapper` class in the `connectivity-apache-httpclient4` module.

## Changes

The changes in this PR include:

- A new block of code in the `HttpClientWrapper` constructor that checks if the destination is configured correctly. If the destination is not configured correctly, it throws a `DestinationAccessException` with an appropriate error message.

The new block of code checks if the destination's `PROXY_TYPE` is `ON_PREMISE` and if the `PROXY_HOST` is empty. If these conditions are met, it further checks if the `TENANT_ID` is empty (indicating a provider) and if the `AUTH_TYPE` (or `AUTH_TYPE_FALLBACK`) is `BASIC_AUTHENTICATION`. If these conditions are met, it throws a `DestinationAccessException` with the message "Accessing an onpremise system on behalf of the provider tenant explicitly is currently not supported." Otherwise, it throws a `DestinationAccessException` with the message "Unable to resolve connectivity service binding."

## Context

This change is part of the effort to migrate the DwC Spring E2E Test, as described in the backlog item. The new feature ensures that the destination is configured correctly before attempting to establish a connection, which helps prevent errors during runtime.

## Reviewer Instructions

Please review the changes in the context of the associated backlog item. Pay particular attention to the new error handling code and ensure that it aligns with the expected behavior described in the backlog item.

2023-11-01 16:57 UTC, newtork commented on cloudplatform/connectivity-apache-httpclient4/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/HttpClientWrapper.java
> +            }
Afaik this limitation is only applicable for DwC not in general.
```suggestion
```

2023-11-01 16:59 UTC, newtork commented on cloudplatform/connectivity-apache-httpclient4/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/HttpClientWrapper.java
> +            throw new DestinationAccessException("Unable to resolve connectivity service binding.");
(Minor)

Maybe this is a good place to encourage looking into the logs?

```suggestion
            throw new DestinationAccessException("Unable to resolve connectivity service binding. Please check the logs.");
```

2023-11-02 08:46 UTC, CharlesDuboisSAP commented on cloudplatform/connectivity-apache-httpclient4/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/HttpClientWrapper.java
> +            }
Removed.

2023-11-02 08:47 UTC, CharlesDuboisSAP commented on cloudplatform/connectivity-apache-httpclient4/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/HttpClientWrapper.java
> +            throw new DestinationAccessException("Unable to resolve connectivity service binding.");
I stored the failed proxy destination and re-throwing it in the HttpClientWrapper. Tell me what you think.

2023-11-02 11:25 UTC, Johannes-Schneider reviewed
I do have some concerns about the suggested solution (see comments).

Furthermore, personally, I think it's a pretty big design flaw to not have the two concerns of **(1)** _I want to connect to a remote system_ and **(2)** _I want to see how my destination in the Destination Service is configured_ (i.e. I just need the properties) separated.

2023-11-02 11:25 UTC, Johannes-Schneider commented on cloudplatform/connectivity-apache-httpclient4/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/HttpClientWrapper.java
> +            new DefaultHttpDestinationBuilderProxyHandler().handle(DefaultHttpDestination.fromDestination(destination));
Personally, I feel like this change isn't a good solution.

Not only does it rely on internal implementation details that might change over time and shouldn't be used outside the `DefaultHttpDestinationBuilder`, but it also isn't guaranteed to actually re-produce the original exception (e.g. the Service Bindings might have changed since we initially created the destination, so this call here might very well succeed).

2023-11-02 11:25 UTC, Johannes-Schneider commented on cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
> +                    return proxyDestination.get();
It feels pretty wrong to silently ignore any exception that might occur here... customers can't even refer to the application logs to see what might have gone wrong.

2023-11-02 13:01 UTC, CharlesDuboisSAP commented on cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
> +                    return proxyDestination.get();
I added a log here.

2023-11-02 13:01 UTC, CharlesDuboisSAP commented on cloudplatform/connectivity-apache-httpclient4/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/HttpClientWrapper.java
> +            new DefaultHttpDestinationBuilderProxyHandler().handle(DefaultHttpDestination.fromDestination(destination));
I added a throw just below just in case the service binding has changed. The destination shouldn't be used anyway.

2023-11-02 13:05 UTC, CharlesDuboisSAP commented
I agree, the two different use cases (reading properties and using the destination) for the same class is a design flaw. But with the timeframe that we have to release v4, I would accept it as tech debt and have usable exceptions messages.
@Johannes-Schneider Do you think the latest commit is better than storing the exception?

2023-11-02 15:21 UTC, Johannes-Schneider requested changes

2023-11-02 15:21 UTC, Johannes-Schneider commented on cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
> +                            proxyDestination.getCause());
I think the details should be included in the cause. So let's not jump to conclusions on this higher abstraction level.

```suggestion
                    log
                        .error(
                            "Unable to resolve proxy details for destination. This destination cannot be used for anything other than reading its properties.",
                            proxyDestination.getCause());
```

2023-11-02 15:21 UTC, Johannes-Schneider commented on cloudplatform/connectivity-apache-httpclient4/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/HttpClientWrapper.java
> +        }
Let's stick what we've aligned on:

```suggestion

        if( destination.getProxyType().contains(ProxyType.ON_PREMISE)
            && destination.getProxyConfiguration().isEmpty() ) {
            throw new DestinationAccessException(
                "Unable to create an HttpClient from the provided destination. "
                    + "The destination is supposed to target an on-premise system but lacks the correct proxy configuration. "
                    + "Please check the application logs for further details.");
        }
```

---

Also: Please apply the same change to the `HttpClient5Wrapper`.

2023-11-03 09:16 UTC, newtork commented on cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
> +                            proxyDestination.getCause());
Unnecessary if condition:

```suggestion
                final String msg =
                    "Unable to resolve proxy configuration for destination. This destination cannot be used for anything other than reading its properties.";
                log.error(msg, proxyDestination.getCause());
```

2023-11-03 09:20 UTC, newtork commented on cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
>                  }
Unnecessary if condition:

```suggestion
                final String msg =
                    "Unable to resolve proxy configuration for destination. This destination cannot be used for anything other than reading its properties.";
                log.error(msg, proxyDestination.getCause());
```

The rest looks good to me :+1:

2023-11-03 09:22 UTC, newtork commented on cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
>                  }
(Comment)

<details>
<summary>The code block could've also just be using regular try-catch for potentially-better(?) readability 🤔</summary>

```suggestion
                try {
                    return proxyHandler.handle(this);
                }
                catch( final Exception e ) {
                    final String msg =
                        "Unable to resolve proxy configuration for destination. This destination cannot be used for anything other than reading its properties.";
                    log.error(msg, e);
                }
```

</details>

(No action required)

2023-11-03 09:23 UTC, newtork approved these changes

2023-11-03 09:26 UTC, CharlesDuboisSAP commented on cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
>                  }
Applied suggestion

2023-11-03 09:32 UTC, newtork submitted a review, later dismissed

2023-11-03 10:00 UTC, Johannes-Schneider commented on cloudplatform/cloudplatform-connectivity/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultHttpDestination.java
> +                // Any change here must be copied to HttpClientWrapper(s) constructors
That comment is no longer true.

```suggestion
```

2023-11-03 11:42 UTC, rnewbigging approved these changes

2023-11-03 12:13 UTC, merged