refactor: Migrate unit tests to JUnit5
SAP/cloud-sdk-java pull request #140
Opened 2023-11-13 16:01 UTC by Johannes-Schneider

# Work in Progress

2023-11-14 12:36 UTC, newtork commented on cloudplatform/caching/pom.xml
> -		<!-- scope "test" -->
(Minor)

I'm perconally in favor of leaving the scope grouping in pom.xml

2023-11-14 12:37 UTC, Johannes-Schneider commented on cloudplatform/caching/pom.xml
> -		<!-- scope "test" -->
Probably an oversight - will fix.

2023-11-14 12:38 UTC, newtork commented on cloudplatform/caching/src/test/java/com/sap/cloud/sdk/cloudplatform/cache/SerializableCacheKeyTest.java
> +    void testSerializableCacheKey()
(Comment)

I ran `mvn clean install` and these package-private classes / methods are being executed :+1:

2023-11-14 12:42 UTC, newtork commented on datamodel/odata-client/pom.xml
> +			<artifactId>mockito-junit-jupiter</artifactId>
(Minor)

Instead of having this additional dependency, maybe we can replace the `@Rule` references in this module?

2023-11-14 12:43 UTC, newtork commented on datamodel/odata-v4/odata-v4-generator-maven-plugin/pom.xml
> +			<version>4.13.2</version>
(Note to myself)

explore why

2023-11-14 12:43 UTC, newtork commented on cloudplatform/connectivity-destination-service/pom.xml
> +			<version>4.13.2</version>
(Note to myself)

Explore why

2023-11-14 12:47 UTC, newtork commented on pom.xml
> -		<junit.version>4.13.2</junit.version>
(Note to myself)

Suggest keeping this line, if junit4 removal is not possible fully.

2023-11-14 12:49 UTC, newtork commented on cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/HttpDestinationPropertiesTest.java
> -@RunWith( MockitoJUnitRunner.class )
(Question)

Huh.. what did that do?

2023-11-14 12:51 UTC, newtork commented on cloudplatform/connectivity-apache-httpclient4/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/CsrfTokenRetrieverTest.java
> +    void testSuccessfulCsrfTokenRetrievalWireMock( @Nonnull final WireMockRuntimeInfo wm )
(Comment)

I still need to get used to parameter based wiremock server :S

2023-11-14 12:55 UTC, Johannes-Schneider commented on cloudplatform/cloudplatform-connectivity/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/HttpDestinationPropertiesTest.java
> -@RunWith( MockitoJUnitRunner.class )
This line was responsible for initializing all the `@Mock` fields in the test class.

2023-11-14 12:59 UTC, newtork commented on cloudplatform/connectivity-apache-httpclient5/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultApacheHttpClient5FactoryTest.java
> +        WireMockExtension.newInstance().options(wireMockConfig().dynamicPort()).build();
(Minor)

Could we move them to method declaration too? I feel like there's no need to have them on class level.

2023-11-14 13:01 UTC, newtork commented on cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServiceAdapterTest.java
> +    void createDefaultBinding( @Nonnull final WireMockRuntimeInfo wm )
(Comment)

Interesting, the wiremock runtime reference is transitively shared with the actual unit test method via `DEFAULT_SERVICE_BINDING`. Looks good!

2023-11-14 13:04 UTC, newtork commented on cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServicePrincipalPropagationTest.java
> +        OAuth2ServiceImpl.clearCache();
(Question)

Why is it necessary(?) now with the change?

2023-11-14 13:06 UTC, newtork commented on cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/GetOrComputeSingleDestinationCommandWithoutAllDestinationsTest.java
> +    void testCorrectIsolationAndCaching( @Nonnull final TestParameters testParameters )
(Comment)

Ugly hard-coded method reference as String. Probably no other way.

2023-11-14 13:07 UTC, newtork commented on cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilderTest.java
> +
(Minor)

Please remove line break

2023-11-14 13:14 UTC, newtork commented on datamodel/odata-client/src/test/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataFetchAsStreamTest.java
> +        WireMockExtension.newInstance().options(wireMockConfig().dynamicPort()).build();
(Minor)

Code wouldn't look better when class property was replaced with method argument?

2023-11-14 13:15 UTC, newtork commented on datamodel/odata-client/src/test/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataHealthyResponseValidatorTest.java
> +        lenient().when(httpResponseStatusLine.getStatusCode()).thenReturn(HttpStatus.SC_OK);
(Minor)

What's with the `lenient()`?

2023-11-14 13:19 UTC, newtork commented on datamodel/odata/odata-core/src/test/java/com/sap/cloud/sdk/datamodel/odata/helper/batch/ODataV2BatchFunctionImportTest.java
> +
(Minor)
new line

2023-11-14 13:24 UTC, newtork commented on datamodel/odata/odata-core/src/test/java/com/sap/cloud/sdk/datamodel/odata/helper/ClientCertificateAuthenticationLocalTest.java
> +        void before()
(Minor)

This code change may not be nessary if `static-dsl` was configured:
https://wiremock.org/docs/junit-jupiter/#configuring-the-static-dsl

What do you think?

2023-11-14 13:30 UTC, newtork commented on datamodel/odata/odata-core/src/test/java/com/sap/cloud/sdk/datamodel/odata/helper/VdmEntityVersionIdentifierTest.java
> +        WireMockExtension.newInstance().options(wireMockConfig().dynamicPort().gzipDisabled(true)).build();
(Question)

Why did you choose static modifier on the `WireMockExtension` fields?

If intentional - why not all-caps the name? :)

2023-11-14 13:33 UTC, newtork commented on datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/core/CollectionValueFunctionRequestBuilderTest.java
> +
(Minor)

New line

2023-11-14 13:35 UTC, newtork commented on datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/core/SingleValueFunctionRequestBuilderTest.java
> +
(Minor)

New line

2023-11-14 13:35 UTC, newtork commented on datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/core/SingleValueFunctionRequestBuilderTest.java
> +
(Minor)

New line

2023-11-14 13:35 UTC, newtork commented on datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/core/SingleValueFunctionRequestBuilderTest.java
> +
(Minor)

New line

2023-11-14 13:40 UTC, Johannes-Schneider commented on cloudplatform/connectivity-destination-service/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DestinationServicePrincipalPropagationTest.java
> +        OAuth2ServiceImpl.clearCache();
This is actually a drive-by change, which is needed due to the "new" OAuth2 cache, @cschubertcs and I introduced recently.
Without this fix, running `mvn clean install` fails on my machine.

2023-11-14 13:54 UTC, Johannes-Schneider commented on datamodel/odata-client/src/test/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataHealthyResponseValidatorTest.java
> +        lenient().when(httpResponseStatusLine.getStatusCode()).thenReturn(HttpStatus.SC_OK);
Mockito complains about "unnecessary mocking" if the mocked method is not actually used, which is the case because we group all the mocking into the setup method even though some methods are not used in every test.
To overcome this issue, Mockito requires the `lenient()` mocker to be used.

2023-11-14 13:57 UTC, Johannes-Schneider commented on datamodel/odata-generator-utility/src/test/java/com/sap/cloud/sdk/datamodel/odata/utility/LegacyClass.java
> +final class LegacyClass
> What's this? Was the old code not working with JUnit5?

Indeed. In the existing test, we used the test class itself to be scanned.
This setup, however, required a non default constructor for the class - this doesn't seem to work with JUnit5.

Making the `LegacyClass` a nested class (inside the corresponding test), unfortunately, also doesn't work as the `LegacyClassScanner` only works with top level classes (where a file exists that is named exactly as the class name).
Therefore, I extracted this class into it's own file.

---

> Why no copyright header?:)

Good catch. Seems like I haven't configured my IntelliJ correclty.

2023-11-14 14:02 UTC, Johannes-Schneider commented on pom.xml
> -		<junit.version>4.13.2</junit.version>
Honestly, I'd like to get rid of JUnit4 in our parent pom.
By doing so, it becomes much harder to accidentally use it in any module (since you would need to specify the version explicitly, which should make you stop and think about what you are currently doing).

2023-11-14 14:36 UTC, Johannes-Schneider commented on datamodel/odata/odata-core/src/test/java/com/sap/cloud/sdk/datamodel/odata/helper/VdmEntityVersionIdentifierTest.java
> +        WireMockExtension.newInstance().options(wireMockConfig().dynamicPort().gzipDisabled(true)).build();
> Why did you choose static modifier on the `WireMockExtension` fields?

IntelliJ suggests so 😅
![image](https://github.com/SAP/cloud-sdk-java/assets/9248711/a6f697d8-ba13-4c05-983b-22a23350d03e)

---

> If intentional - why not all-caps the name? :)

Done.

2023-11-14 14:53 UTC, Johannes-Schneider commented on cloudplatform/connectivity-apache-httpclient5/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/DefaultApacheHttpClient5FactoryTest.java
> +        WireMockExtension.newInstance().options(wireMockConfig().dynamicPort()).build();
Not sure how this would work with two wiremock servers required... didn't test it. Also: I wanted to change as little about our tests as possible.
But we could consider some more clean up in a follow up PR.

2023-11-14 14:54 UTC, Johannes-Schneider commented on datamodel/odata-client/src/test/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataFetchAsStreamTest.java
> +        WireMockExtension.newInstance().options(wireMockConfig().dynamicPort()).build();
I'd need to modify all test methods and our internal assertion method (which uses the class field)... So to keep the changes as minimal as possible, I'd like to not do this change now.
Can be considered in a follow up PR, though.

2023-11-14 15:03 UTC, Johannes-Schneider commented on s4hana/rfc/src/test/java/com/sap/cloud/sdk/s4hana/connectivity/rfc/JCoTransactionValueTest.java
> +        lenient().when(exportParameters.getTable(TABLE_NAME)).thenReturn(table);
[explanation](https://github.com/SAP/cloud-sdk-java/pull/140#discussion_r1392617386)

2023-11-14 15:31 UTC, Johannes-Schneider commented on datamodel/odata-client/src/test/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataHealthyResponseValidatorTest.java
> +        lenient().when(httpResponseStatusLine.getStatusCode()).thenReturn(HttpStatus.SC_OK);
These methods are used (I assume, didn't check closely) - just not all in every test case.
So we could move the correct set of mockings to the individual test methods, but this would result in a lot of duplicated code.

2023-11-14 17:21 UTC, newtork commented on datamodel/odata-client/src/test/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataHealthyResponseValidatorTest.java
> +        lenient().when(httpResponseStatusLine.getStatusCode()).thenReturn(HttpStatus.SC_OK);
Yeah.. not best practice, but reasonable compromise.

2023-11-15 08:08 UTC, Johannes-Schneider commented on datamodel/odata/odata-core/src/test/java/com/sap/cloud/sdk/datamodel/odata/helper/ClientCertificateAuthenticationLocalTest.java
> +        void before()
Done in [b8dc83d](https://github.com/SAP/cloud-sdk-java/pull/140/commits/b8dc83d41291e770ad731a1536c8c14369efc80e)

2023-11-15 08:11 UTC, Johannes-Schneider commented on datamodel/odata-client/pom.xml
> +			<artifactId>mockito-junit-jupiter</artifactId>
Done in [3eab3af](https://github.com/SAP/cloud-sdk-java/pull/140/commits/3eab3afd05117c494c2f33f47036f6026548ba77).

2023-11-15 10:14 UTC, newtork commented on .github/workflows/build.yaml
> +          mvn --batch-mode --no-transfer-progress --fail-at-end --show-version --threads 1 org.jacoco:jacoco-maven-plugin:prepare-agent surefire:test org.jacoco:jacoco-maven-plugin:report
to be discussed

2023-11-16 08:42 UTC, newtork submitted a review, later dismissed

2023-11-16 08:42 UTC, newtork commented on datamodel/odata-v4/odata-v4-generator-maven-plugin/pom.xml
> +			<version>4.13.2</version>
Some investigation and potential workaround happening here ifactId>junit-platform-commons</

2023-11-16 10:35 UTC, CharlesDuboisSAP requested changes

2023-11-16 10:35 UTC, CharlesDuboisSAP commented on .github/workflows/build.yaml
> +  MVN_CLI_ARGS_SINGLE_THREAD: "--batch-mode --no-transfer-progress --fail-at-end --show-version"
Why not use `@Execution(ExecutionMode.SAME_THREAD)` on the broken tests instead?

2023-11-16 10:35 UTC, CharlesDuboisSAP commented on datamodel/odata/odata-core/src/test/java/com/sap/cloud/sdk/datamodel/odata/helper/ServicePathTest.java
>  public class ServicePathTest
remove public

2023-11-16 10:35 UTC, CharlesDuboisSAP commented on archetypes/scp-cf-spring-jakarta/src/main/resources/archetype-resources/application/src/test/java/__packageInPathFormat__/UnitTest.java
> +    public void test()
Remove public

2023-11-16 10:35 UTC, CharlesDuboisSAP commented on datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/core/UpdateRequestHelperPatchTest.java
>          throws Exception
Remove public (also line 611 and 626)

2023-11-16 12:43 UTC, Johannes-Schneider commented on .github/workflows/build.yaml
> +  MVN_CLI_ARGS_SINGLE_THREAD: "--batch-mode --no-transfer-progress --fail-at-end --show-version"
Good idea! Let me try that.

2023-11-16 13:22 UTC, CharlesDuboisSAP commented on datamodel/odata-generator-utility/src/test/java/com/sap/cloud/sdk/datamodel/odata/utility/S4HanaNamingStrategyTest.java
>          void
This just uncovers more public keywords to be removed 😁

2023-11-16 13:32 UTC, Johannes-Schneider commented on .github/workflows/build.yaml
> +  MVN_CLI_ARGS_SINGLE_THREAD: "--batch-mode --no-transfer-progress --fail-at-end --show-version"
Unfortunately, using `@Execution` is not sufficient for preventing the pipeline to get (seemingly) overloaded 😔
See [this test step](https://github.com/SAP/cloud-sdk-java/actions/runs/6891172710/job/18745796606?pr=140#step:9:20964) for an example.

2023-11-16 14:09 UTC, CharlesDuboisSAP commented on .github/workflows/build.yaml
> +  MVN_CLI_ARGS_SINGLE_THREAD: "--batch-mode --no-transfer-progress --fail-at-end --show-version"
Can you screenshot the link it goes to a random line. I only see those two test failing (seems to be unrelated)
![image](https://github.com/SAP/cloud-sdk-java/assets/103174266/02c77eab-5e83-4246-89ee-66c26846a71c)

2023-11-16 14:15 UTC, Johannes-Schneider commented on .github/workflows/build.yaml
> +  MVN_CLI_ARGS_SINGLE_THREAD: "--batch-mode --no-transfer-progress --fail-at-end --show-version"
Sure

![image](https://github.com/SAP/cloud-sdk-java/assets/9248711/adf28781-fb55-4130-8a29-e9e322e4543f)

2023-11-16 14:39 UTC, CharlesDuboisSAP approved these changes

2023-11-16 14:58 UTC, merged