refactor: Switch to "Spring 17" Stack
SAP/cloud-sdk-java pull request #142
Opened 2023-11-14 14:24 UTC by Johannes-Schneider

## Context
 

SAP/cloud-sdk-java-backlog#351.

This PR performs the following dependency updates:

* Required minimum Java version: `8` → `17`
* XSUAA Client Lib version: `2.14.2` → `3.2.1`
* Spring version (internal only): `5.3.29` → `6.0.13`
* Spring security version (internal only): `5.8.6` → `6.1.5`
* Wiremock version (internal only): `2.35.1` → `3.3.1`
* Jetty version (internal only): `9.4.53.v20231009` → `11.0.18`

Additionally, following changes have been done:

* **Remove** `scp-cf-spring` archetype (→ "Spring 8" stack is no longer supported)
* **Remove** `servlet` module (→ no longer supported)
* **Replace** `servlet` with `servlet-jakarta` in `scp-cf`

## Definition of Done

- [x] ~Functionality scope stated & covered~
- [x] Tests cover the scope above
- [ ] ~Error handling created / updated & covered by the tests above~
- [ ] Documentation updated
- [x] Release notes updated

2023-11-17 12:37 UTC, CharlesDuboisSAP requested changes
Dependency `javax.servlet-api` is still present in soap, bom, tenant and pom?

2023-11-17 12:37 UTC, CharlesDuboisSAP commented on bom/pom.xml
> -		<!-- see https://central.sonatype.com/artifact/com.sap.cloud.sjb.cf/sap-java-buildpack-bom/ -->
Should this be moved into an easily revertable SJB PR?

2023-11-17 12:37 UTC, CharlesDuboisSAP commented on datamodel/openapi/openapi-core/src/main/java/com/sap/cloud/sdk/services/openapi/apiclient/ApiClient.java
> +            httpRequestFactory.setHttpClient(ApacheHttpClient5Accessor.getHttpClient(destination));
Do we need to remove the `connectivity-apache-httpclient4` module?

2023-11-17 12:37 UTC, CharlesDuboisSAP commented on pom.xml
>  		<slf4j.version>1.7.36</slf4j.version>
Update slf4j to 2.0.9

2023-11-17 13:15 UTC, Johannes-Schneider commented on datamodel/openapi/openapi-core/src/main/java/com/sap/cloud/sdk/services/openapi/apiclient/ApiClient.java
> +            httpRequestFactory.setHttpClient(ApacheHttpClient5Accessor.getHttpClient(destination));
No. All of our internal code is based on the Apache V4 Http client.

2023-11-17 13:17 UTC, Johannes-Schneider commented on pom.xml
>  		<slf4j.version>1.7.36</slf4j.version>
Good catch 👍

2023-11-17 13:47 UTC, CharlesDuboisSAP commented on datamodel/openapi/openapi-core/src/main/java/com/sap/cloud/sdk/services/openapi/apiclient/ApiClient.java
> +            httpRequestFactory.setHttpClient(ApacheHttpClient5Accessor.getHttpClient(destination));
Can you explain this change?

2023-11-20 08:48 UTC, Johannes-Schneider commented on datamodel/openapi/openapi-core/src/main/java/com/sap/cloud/sdk/services/openapi/apiclient/ApiClient.java
> +            httpRequestFactory.setHttpClient(ApacheHttpClient5Accessor.getHttpClient(destination));
What I'm doing here is to replace our currently "compatibility workaround" (i.e. support for Spring 5 **AND** Spring 6 in the `openapi-core` module) with a proper implementation that support Spring 6 **ONLY**.

(Before that change, we used reflection to enable support for both major versions of Spring. In our discussion last Tuesday, however, we decided to drop support for Spring 5 entirely. So the workaround is no longer needed)

In this very specific case, we need to use our `ApacheHttpClient5Accessor` since Spring 6's `RestTemplate` now requires an Apache Http Client v5.

2023-11-23 12:28 UTC, CharlesDuboisSAP reviewed
All commits since my last review look good to me. I still think we should keep the SJB comment https://github.com/SAP/cloud-sdk-java/pull/142/files#r1397206086

2023-11-23 12:28 UTC, CharlesDuboisSAP commented on release_notes_next_major.md
> +- The SAP Cloud SDK version 5 is no longer compatible with Spring version 5, the [XSUAA Client Library](https://github.com/SAP/cloud-security-services-integration-library) version 2, and the SAP Java
also not compatible with TomEE 8 and 9

2023-11-23 12:28 UTC, CharlesDuboisSAP commented on release_notes_next_major.md
> +      - Update `org.springframework.spring-framework-bom` from `5.3.29` to `6.0.13`. **Note** This dependency is used by the SDK **internally only**. In other words: This update **does not** affect c
```suggestion
      - Update `org.springframework:spring-framework-bom` from `5.3.29` to `6.0.13`. **Note** This dependency is used by the SDK **internally only**. In other words: This update **does not** affect consuming projects that use the `sdk-bom` for dependency management.
```

2023-11-23 12:28 UTC, CharlesDuboisSAP commented on release_notes_next_major.md
> +      - Update `org.slf4j:slf4j-api` from `1.7.36` to `2.0.9`
Internal dependencies in the release notes?

2023-11-23 12:42 UTC, KavithaSiva commented on release_notes_next_major.md
> +      - Update `org.slf4j:slf4j-api` from `1.7.36` to `2.0.9`
I guess, with the additional internal note, this should be okay to include in the release note.

2023-11-23 12:52 UTC, CharlesDuboisSAP commented on release_notes_next_major.md
> +      - Update `org.slf4j:slf4j-api` from `1.7.36` to `2.0.9`
slf4j does not have it, also I updated many dependencies without adding them in the release notes (see [Fix Blackduck v5 findings#319](https://github.com/SAP/cloud-sdk-java-backlog/issues/319))

2023-11-23 12:56 UTC, KavithaSiva commented on bom/pom.xml
> -		<!-- see https://central.sonatype.com/artifact/com.sap.cloud.sjb.cf/sap-java-buildpack-bom/ -->
I think for now we can safely remove this comment as the new sap java buildpack is not available and we don't have anything to check compatibility against. 

Also, I am not sure yet if we still intend to always maintain compatibility with the SAP java buildpack if we don't have jco related code in v5 anyway. Can be tested instead in the TomEE test AFAIK.

2023-11-23 13:09 UTC, Johannes-Schneider commented on release_notes_next_major.md
> +      - Update `org.slf4j:slf4j-api` from `1.7.36` to `2.0.9`
* `slf4j-api` is actually a dependency we are managing for customers, so that definitely belongs into our release notes
* I also added Spring here because it has quite some implications (i.e. no more support for Spring 5 whatsoever). But as we also added an additional compatibility note, no strong opinion.

2023-11-23 17:59 UTC, MatKuhr commented on bom/pom.xml
> -		<!-- see https://central.sonatype.com/artifact/com.sap.cloud.sjb.cf/sap-java-buildpack-bom/ -->
We have JCo related code in v5. Currently it will not be released, but starting with SJB v2 it will be released again. From then we again need to maintain compatibility with SJB v2.

2023-11-23 18:11 UTC, MatKuhr approved these changes
otherwise lgtm!

2023-11-23 18:11 UTC, MatKuhr commented on archetypes/scp-cf-spring-jakarta/src/main/resources/archetype-resources/manifest.yml
> -    - sap_java_buildpack
This is maybe controversial, why not leave the SJB in as is? 
AFAIK it brings HANA drivers which may be useful for apps. No strong opinion though..

2023-11-23 18:11 UTC, MatKuhr commented on pom.xml
> -											<exclude>javax.servlet:servlet-api</exclude>
wouldn't it be useful to keep this banned?

2023-11-24 07:53 UTC, Johannes-Schneider commented on archetypes/scp-cf-spring-jakarta/src/main/resources/archetype-resources/manifest.yml
> -    - sap_java_buildpack
I didn't consider that only `war` deployment is of course affected by our "no longer supported" decision.
So we could definitely switch back to the SJB, if we wanted.

2023-11-24 07:53 UTC, Johannes-Schneider commented on pom.xml
> -											<exclude>javax.servlet:servlet-api</exclude>
Actually yes, good catch.

2023-11-24 08:04 UTC, Johannes-Schneider commented on archetypes/scp-cf-spring-jakarta/src/main/resources/archetype-resources/manifest.yml
> -    - sap_java_buildpack
Switched back in [63a899d](https://github.com/SAP/cloud-sdk-java/pull/142/commits/63a899d4fac5770059be09684956cae11b05ac6a)

2023-11-24 08:05 UTC, Johannes-Schneider commented on pom.xml
> -											<exclude>javax.servlet:servlet-api</exclude>
Reverted this change in [63a899d](https://github.com/SAP/cloud-sdk-java/pull/142/commits/63a899d4fac5770059be09684956cae11b05ac6a)

2023-11-24 08:10 UTC, Johannes-Schneider commented on bom/pom.xml
> -		<!-- see https://central.sonatype.com/artifact/com.sap.cloud.sjb.cf/sap-java-buildpack-bom/ -->
I added some corresponding comments in [afa5330](https://github.com/SAP/cloud-sdk-java/pull/142/commits/afa533097cdbd6eb263628de677f47b93d2dc46f).

2023-11-24 08:40 UTC, CharlesDuboisSAP approved these changes

2023-11-24 08:40 UTC, merged