readme expanded and formatted
SAP/cloud-sdk-java pull request #148
Opened 2023-11-20 08:39 UTC by rnewbigging

## Context
 

SAP/cloud-sdk-java-backlog#345

Expanded the ReadMe for legibility and additional resources, including use cases, documentation links, and table of contents.

### Feature scope:

 
- [x] Name and description
- [x] Table of contents
- [x] Version 5 migration
- [ ] Installation steps
- [x] Use Cases
    - [x] OData
    - [x] OpenAPI
    - [x] Connectivity
- [x] Release Notes link
- [x] Support
- [x] Contribution
- [x] Documentation link
- [x] Tutorial link 

## Definition of Done

- [x] Functionality scope stated & covered
- [ ] ~Tests cover the scope above~
- [ ] ~Error handling created / updated & covered by the tests above~
- [ ] ~Documentation updated~
- [ ] ~Release notes updated~

2023-11-20 08:44 UTC, rnewbigging commented on README.md
>  ## Requirements and Setup
Is the given link to the "getting started" documentation sufficient or do we want this expanded?

2023-11-20 08:46 UTC, rnewbigging commented on README.md
Is the given link to the "getting started" documentation sufficient or do we want this expanded?

2023-11-20 09:19 UTC, CharlesDuboisSAP requested changes
The build badge is broken 
![image](https://github.com/SAP/cloud-sdk-java/assets/103174266/2fd6d976-aa66-4702-b87b-195f3a342f1b)
And the maven central badge should point to v5

2023-11-20 09:19 UTC, CharlesDuboisSAP commented on CONTRIBUTING.md
> +When your contribution is ready, please open a pull request using the [provided template](https://github.com/SAP/cloud-sdk-java/blob/main/.github/PULL_REQUEST_TEMPLATE.md).
```suggestion
When your contribution is ready, please open a [pull request](https://github.com/SAP/cloud-sdk-java/compare).
```

2023-11-20 09:19 UTC, CharlesDuboisSAP commented on README.md
> +- For an overview of the latest change, please refer to our [release notes.](https://sap.github.io/cloud-sdk/docs/java/v5/release-notes).
```suggestion
- For an overview of the latest changes, please refer to our [release notes.](https://sap.github.io/cloud-sdk/docs/java/v5/release-notes).
```

2023-11-21 10:40 UTC, cschubertcs approved these changes

2023-11-21 10:57 UTC, merged