fix: DwC Connectivity Service Auto Configuration
SAP/cloud-sdk-java pull request #149
Opened 2023-11-20 16:01 UTC by MatKuhr

## Context

SAP/cloud-sdk-java-backlog#209

This PR changes the connectivity service binding for megaclite to no longer be registered by default. This is necessary as otherwise there would be two bindings available in case shared orbits are used.

Users will have to register the connectivity binding explicitly, similar to the destination service binding.

### Feature scope:
 
- [ ] Make `CONNECTIVITY_BINDING` public
- [ ] Update DwC Documentation & Migration Guide

## Definition of Done

- [x] Functionality scope stated & covered
- [x] Tests cover the scope above
- [x] ~Error handling created / updated & covered by the tests above~
- [ ] Documentation updated
- [x] ~Release notes updated~

2023-11-20 18:23 UTC, newtork commented on cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingAccessor.java
> +    public static final MegacliteServiceBinding CONNECTIVITY_BINDING =
(Major)

I think this behavior change requires a proper release, doesn't it?

2023-11-21 07:56 UTC, MatKuhr commented on cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingAccessor.java
> +    public static final MegacliteServiceBinding CONNECTIVITY_BINDING =
Do you mean release note? Since this only affects DwC users I was thinking to have this in the DwC docs only. We did it similarly for other DwC related API changes IIRC.

2023-11-21 14:03 UTC, Johannes-Schneider requested changes

2023-11-21 14:03 UTC, Johannes-Schneider commented on cloudplatform/connectivity-dwc/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/MegacliteServiceBindingAccessor.java
> -    }
We are using the same code again in the `clearServiceBindings` method (line `67`).
I'd say let's also remove it from there.

2023-11-22 07:46 UTC, Johannes-Schneider approved these changes
Changes LGTM - I think we should start something like a `release_notes_dwc_next_snapshot.md` to keep track of (future) changes.

2023-11-22 07:46 UTC, merged