chore: Rename scp-cf-spring-jakarta archetype to spring-boot3
SAP/cloud-sdk-java pull request #153
Opened 2023-11-23 10:17 UTC by CharlesDuboisSAP

# Pull Request Description🤖

## Summary
This PR addresses the backlog item [#356](https://github.com/SAP/cloud-sdk-java-backlog/issues/356). It involves renaming the `scp-cf-spring-jakarta` archetype to `spring-boot3` to provide a more meaningful name.

## Changes
- The `scp-cf-spring-jakarta` archetype has been renamed to `spring-boot3` in the following GitHub workflow files: `build-sanity.yaml`, `build.yaml`, `deploy_snapshot.yaml`, and `prepare_release.yml`.
- The `scp-cf-spring-jakarta` module has been renamed to `spring-boot3` in the `archetypes/pom.xml` file.
- The `scp-cf-spring-jakarta` artifactId has been renamed to `spring-boot3` in the `archetypes/spring-boot3/pom.xml` file.
- The `scp-cf-spring-jakarta` artifactId has been renamed to `spring-boot3` in the `module-inventory.json` file.
- All files under the `archetypes/scp-cf-spring-jakarta` directory have been moved to the `archetypes/spring-boot3` directory.

## Reviewer Instructions
Please review the changes and ensure that all references to `scp-cf-spring-jakarta` have been correctly updated to `spring-boot3`.

2023-11-23 12:03 UTC, MatKuhr reviewed
Personally I feel `spring-boot-3` would look slightly better, but no strong opinion

2023-11-28 09:41 UTC, newtork requested changes
According to our other modules with version numbers, I expect it to be:
```diff
- spring-boot-3
+ spring-boot3
```

2023-11-28 15:03 UTC, Johannes-Schneider commented on archetypes/spring-boot3/src/main/resources/archetype-resources/manifest.yml
> +    - java_buildpack
Why did we change it back to the community buildpack?
(For context: `jar` deployment is still supported using the SAP Java Buildpack. We only dropped support for `war` deployments)

2023-11-28 15:03 UTC, Johannes-Schneider commented on .github/workflows/build.yaml
> +              "archetype": "spring-boot3",
(info)

We still need to update our GitHub config since we changed this name.

2023-11-28 15:08 UTC, CharlesDuboisSAP commented on archetypes/spring-boot3/src/main/resources/archetype-resources/manifest.yml
> +    - java_buildpack
Unwanted changed, I removed it

2023-11-28 15:09 UTC, CharlesDuboisSAP commented on .github/workflows/build.yaml
> +              "archetype": "spring-boot3",
It was updated

2023-11-29 07:43 UTC, Johannes-Schneider approved these changes
LGTM - please remember to update our documentation

2023-11-29 08:00 UTC, merged