fix: [Destinations] Improve Caching for Service Binding Destinations
SAP/cloud-sdk-java pull request #212
Opened 2024-01-05 15:58 UTC by MatKuhr

## Context

This PR improves caching for destinations loaded from OAuth service bindings. It removes the random UUID from the destination name, causing two improvements:

- The resilience for token flows will now be applied correctly across the same OAuth service, even when destination instances are different
- The destinations now use the same HttpClient

Blocked by findings in #211 

### Feature scope:
 
- [ ] Ensure HTTP clients will be reused
- [ ] Task2 
  - [ ] SubTask1 

## Definition of Done

- [ ] Functionality scope stated & covered
- [ ] Tests cover the scope above
- [ ] ~Error handling created / updated & covered by the tests above~
- [ ] ~Documentation updated~
- [ ] ~Release notes updated~

2024-01-15 17:14 UTC, MatKuhr commented on cloudplatform/resilience/src/test/java/com/sap/cloud/sdk/cloudplatform/resilience/ResilienceConfigurationTest.java
> +        assertThat(configNoParameters).isEqualTo(builder.withoutParameters());
Driveby test improvements

2024-01-15 17:15 UTC, MatKuhr commented on cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceTest.java
> +    private static final String RESPONSE_TEMPLATE = """
moved over from `OnPremTest` as the tests are unrelated to any on-prem specifics

2024-01-15 17:17 UTC, MatKuhr commented on cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceTest.java
> +        sut = new OAuth2Service(SERVER_1.baseUrl(), IDENTITY_1, TECHNICAL_USER_CURRENT_TENANT);
enhancement compared to old test

2024-01-16 10:44 UTC, Johannes-Schneider requested changes
I reviewed the production code only.

In there, I'd like to not use the client id as part of the destination name.

2024-01-16 10:44 UTC, Johannes-Schneider commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2Service.java
> +                .of(identity.getId())
[question]

Why are we using the `identity` here as the "key" for our resilience?
I would have expected the `uri` to be used.

That way, we would apply resilience (i.e. bulkheads) correctly towards the target system.
In contrast to that (i.e. if we were using the `identity`), we would create a new resilience for the same target service if the binding was rotated recently.

Or am I overlooking something here?

2024-01-16 10:44 UTC, Johannes-Schneider commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilder.java
> +            destinationBuilder.name(client.getId());
[major]

The `client.getId()` could be considered confidential. Therefore, I wouldn't want to use it as the destination name.

2024-01-16 10:44 UTC, Johannes-Schneider commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBindingDestinationLoader.java
> +                + clientIdentity.getId();
[major]

Same remark as above: The `clientIdentity.getId()` is confidential and, therefore, shouldn't be used as a destination name IMO.

2024-01-16 11:15 UTC, MatKuhr commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilder.java
> +            destinationBuilder.name(client.getId());
why would it be confidential? I'd say it's exactly the opposite, this is what you (need to) share publicly. For example, the client ID is also used for reuse services to perform callbacks to an application ([src](https://github.wdf.sap.corp/CPSecurity/Knowledge-Base/blob/master/03_ApplicationSecurity/ProofOfPossession.md#rules-for-token-requests-and-token-forwarding)).

2024-01-16 11:18 UTC, MatKuhr commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2Service.java
> +                .of(identity.getId())
the resilience is applied for the token flows only, not the target system. We could use the tokenUrl as key, but this is probably not isolated enough, since the tokenUrl is typically shared for many (if not all) different OAuth flows. If one service is misconfigured, the circuit breaker could block all other token flows. 

E.g. let's say you are using 5 different services, one of them being the destination service. Now assume you include the destination service in your SaaS registry callback and token requests for it are failing. Now the other 4 services are also blocked (assuming the circuit breaker is triggered by that).

2024-01-16 12:21 UTC, Johannes-Schneider commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilder.java
> +            destinationBuilder.name(client.getId());
From the linked documentation, I assume you talking about following:

> Hereafter the cases, where token forwarding are **not going to work** and a new token must be requested explicitly:
> 
> [ ... ]
> 
> Reuse Service
> - to Consumer Application
>   - request [consumer-specific token](#consumer-specific-token) with `resource` parameter according to [RFC 8707](https://datatracker.ietf.org/doc/html/rfc8707) <br>``resource`` = ``urn:sap:identity:consumer:clientid:<consumer client id>``

If so, I wouldn't call it _"this is what you (need to) share publicly"_.
Sure, you need to include your `clientid` when fetching that particular token - but that is of course also true for fetching any other token, right?
(I.e. We have to send out `clientid` and even the `clientsecret` to an XSUAA instance in order to retrieve some access token for a specific service)

And even if the returned token is then forwarded to the target system (which will then use it to trigger the application's callback, ultimately), I'd still argue that the token itself is of course also confidential.
You wouldn't share your authorization token publicly, would you?

At least this is how I would think of the entire situation.
Maybe I'm missing some important information or I'm just plain wrong here.

2024-01-16 12:36 UTC, MatKuhr commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilder.java
> +            destinationBuilder.name(client.getId());
> Sure, you need to include your clientid when fetching that particular token - but that is of course also true for fetching any other token, right?

Not really, at least not how I understand it. In this example the requester is actually including the client ID of the other application in addition to its own (i.e. you get a call A -> B, B remembers the client ID of A from that call and then requests a token from IAS using both client IDs A and B)

While the signed token is confidential of course, the decoded content i.e. its claims are generally not. Of course, you can potentially have PII in there (e.g. email address) which would be subject to other concerns regarding DPP, but the client id doesn't fall in that category as it is a technical ID

2024-01-16 13:46 UTC, Johannes-Schneider commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilder.java
> +            destinationBuilder.name(client.getId());
Okay, I think [this documentation](https://github.wdf.sap.corp/CPSecurity/Knowledge-Base/blob/master/03_ApplicationSecurity/ProofOfPossession.md#service-consumer-specific-token) makes things bit clearer.

Here, the cURL request contains two different `clientid`s, just as you explained, @MatKuhr:

```bash
curl --cert certificate.pem --key key.pem \
     -X POST https://<<customer tenant host>>/oauth2/token \ 
     -d 'grant_type=client_credentials&client_id=<<clientid>>&resource=urn:sap:identity:consumer:clientid:<<consumer identifier>>'
```

(There is the `clientid` and `consumer identifier`, which I assume to be a `clientid` as well, judging from the resource name)

2024-01-16 13:53 UTC, Johannes-Schneider commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2Service.java
> +                .of(identity.getId())
> the resilience is applied for the token flows only, not the target system.

Yes, true. I meant the token service when I said _"target system"_.

---

> We could use the tokenUrl as key, but this is probably not isolated enough

mhmm.. I see.
So it would be nice if we could apply the bulkhead on a "per URL" basis but keep the circuit breakers isolated per "identity"... 🤔

Could be done if we really wanted to (i.e. we could nest two resilient calls) but it's probably not worth the extra code complexity.

2024-01-16 14:09 UTC, MatKuhr commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2Service.java
> +                .of(identity.getId())
Yes, for now I figured the most straight-forward is to apply the resilience patterns on the same level. The bulkhead generally makes sense to line up with the rate limit on the server side. I'm not 100% sure how to interpret [this document](https://github.wdf.sap.corp/CPSecurity/Knowledge-Base/blob/master/03_ApplicationSecurity/RateLimit.md) on the XSUAA limits, but it sounds like it's per sub account, so we probably could generalize to the token URL and use a much higher value than the default (50) as size. But I don't think it's super needed and error handling is probably much easier if its isolated on client ID.

2024-01-16 14:24 UTC, MatKuhr commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilder.java
> +            destinationBuilder.name(client.getId());
Yes this is what I meant 👍🏻 

But that is ofc not a super strong indicator, so I finally found an explicit statement about this topic in the [relevant RFC](https://datatracker.ietf.org/doc/html/rfc6749#section-2.2) now which states the ID is not a secret:

> The client identifier is not a secret; it is exposed to the resource owner and MUST NOT be used
   alone for client authentication.
   
Of course, having it makes a guessing attack easier in theory, but the client secret is a generated secret for technical auth only (and not a user password) so there is no excuse for it being so short that it can be guessed.

2024-01-16 14:40 UTC, Johannes-Schneider commented on cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceBindingDestinationLoaderTest.java
> +            .isNotSameAs(result);
[minor]

Duplicated assertion.

```suggestion
            .isEqualTo(result);
```

2024-01-16 14:40 UTC, Johannes-Schneider commented on cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceTest.java
> +        final OAuth2Service service2 = new OAuth2Service(SERVER_2.baseUrl(), IDENTITY_1, TECHNICAL_USER_CURRENT_TENANT);
In this test, we even anticipated the super-edge-case where two services (coincidentally) shared the exact same client identity.

Right now, our updated resilience configuration would NOT separate those two services.

Should we add the token service URI to the resilience config "key" to match this implementation detail?

2024-01-16 16:10 UTC, MatKuhr commented on cloudplatform/connectivity-oauth/src/test/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2ServiceTest.java
> +        final OAuth2Service service2 = new OAuth2Service(SERVER_2.baseUrl(), IDENTITY_1, TECHNICAL_USER_CURRENT_TENANT);
Good point, I added the URL in now. Although unlikely, it's probably still better to have it in. Although we currently only support XSUAA as auth server and there the IDs are guaranteed to be unique. But once we add IAS this is probably no longer the case..

2024-01-17 07:46 UTC, Johannes-Schneider commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilder.java
> +            destinationBuilder.name(client.getId());
Thanks for digging up that RFC.

I'm still wondering whether customers also know about this (I highly doubt it, honestly).
So I'm afraid we will see issue coming our way that claim that we are "exposing client secrets" in our logging.
We would then need to remember that this is indeed not an issue and then also find the link you just posted... Not very lightweight on the support facilitator's shoulders IMO.

So how about we use something like the following for the destination's name: `"Programatic Destination " + identity.getId().hashCode()`

Something like this would, in theory, introduce the "risk" of having equal names for different destinations (due to possible hash collisions), but that shouldn't be an issue for our HttpClient caching as the name is ofc not the only property that is considered.

Any opinions about that?

2024-01-17 12:48 UTC, newtork commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilder.java
> +            destinationBuilder.name(client.getId());
(OT)
```diff
 - "Programatic Destination " + identity.getId().hashCode()
 +  "Programatic Destination " + AtomicInteger#getAndIncrement()
 ```

2024-01-17 14:16 UTC, MatKuhr commented on cloudplatform/connectivity-oauth/src/main/java/com/sap/cloud/sdk/cloudplatform/connectivity/OAuth2DestinationBuilder.java
> +            destinationBuilder.name(client.getId());
Discussed offline, used the hash code solution for now 👍🏻

2024-01-17 14:44 UTC, Johannes-Schneider approved these changes
LGTM

2024-01-17 14:47 UTC, merged