Improve release workflow
SAP/cloud-sdk-java pull request #39
Opened 2023-09-05 10:54 UTC by KevinHudemann

BLI: https://github.com/SAP/cloud-sdk-java-backlog/issues/282

Release workflow:
- trigger the [prepare release workflow](https://github.com/SAP/cloud-sdk-java/actions/workflows/prepare_release.yml)
- Check/approve PR and publish the release
- perform release workflow will be triggered once the release is published

Example draft release: https://github.com/SAP/cloud-sdk-java/releases/tag/untagged-df758d5dc3827df5f1d8
Example PR that gets created when triggering the `prepare_release` workflow (although from the wrong branch, would be main): https://github.com/SAP/cloud-sdk-java/pull/38

2023-09-05 12:30 UTC, Johannes-Schneider commented on .github/workflows/prepare_release.yml
> +  build:
I'm wondering whether we can somehow circumvent to (more or less) copy & paste the entire CI pipeline into this pipeline.

Idea:
What if we would use the [wait on check](https://github.com/marketplace/actions/wait-on-check) action after we have updated the version to our release version and created the PR.
That way, we could wait with the second commit (setting the version to the next snapshot version) until the CI pipeline on our newly created PR went through successfully.

Problem could be that we cannot access the built `*.jar` files (maybe?).

2023-09-05 12:37 UTC, daniel-kurzynski commented on .github/workflows/prepare_release.yml
> +  build:
> Problem could be that we cannot access the built *.jar files (maybe?).

We also hat a long discussion about that. But essentially the reason was that we want to assure to build only once and would somehow get the artifacts copied over. 
Alternative would have been to merge o master and trigger the release by that event, using the main pipeline to create the release draft ...
But finally we thought, the pipeline structure is less complex if we just have different pipelines, although we have to duplicate some parts.

2023-09-05 12:42 UTC, daniel-kurzynski commented on .github/workflows/prepare_release.yml
> +  build:
I guess we could discuss to extracts some pipeline parts into reusable actions.

2023-09-05 12:44 UTC, daniel-kurzynski commented on .github/workflows/prepare_release.yml
> +  build:
Btw. I guess the the release pipeline might be different from the main. It is rather similar to the sanity build, but might include more, e.g. blackduck, etc ...

2023-09-06 08:18 UTC, Johannes-Schneider requested changes
Please make sure to not release any of our _not to be released_ modules.

2023-09-06 08:18 UTC, Johannes-Schneider commented on .github/workflows/prepare_release.yml
> +    needs: [archetypes, codeql, prepare-release]
I think we should include Blackduck and Fosstar before actually performing the release.

2023-09-06 08:18 UTC, Johannes-Schneider commented on .github/workflows/prepare_release.yml
> +          mvn $MVN_CLI_ARGS install jacoco:report org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy -DaltReleaseDeploymentRepository=local::file:./rel-${{ needs.prepare-release.outputs.releas
This command doesn't exclude our _not to be released_ modules yet, right?

2023-09-06 08:19 UTC, KevinHudemann commented on .github/workflows/prepare_release.yml
> +          mvn $MVN_CLI_ARGS install jacoco:report org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy -DaltReleaseDeploymentRepository=local::file:./rel-${{ needs.prepare-release.outputs.releas
That's true but also part of another BLI (https://github.com/SAP/cloud-sdk-java-backlog/issues/90) 🙂

2023-09-06 08:21 UTC, KevinHudemann commented on .github/workflows/prepare_release.yml
> +          mvn $MVN_CLI_ARGS install jacoco:report org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy -DaltReleaseDeploymentRepository=local::file:./rel-${{ needs.prepare-release.outputs.releas
And we don't release anything yet.

2023-09-06 08:24 UTC, Johannes-Schneider commented on .github/workflows/prepare_release.yml
> +          mvn $MVN_CLI_ARGS install jacoco:report org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy -DaltReleaseDeploymentRepository=local::file:./rel-${{ needs.prepare-release.outputs.releas
> That's true but also part of another BLI (https://github.com/SAP/cloud-sdk-java-backlog/issues/90) 🙂

Ah okay, wasn't aware.

> And we don't release anything yet.

Yes, but the modules will be part of the draft release (attached as a `zip` file), right?
So technically consumers could download compiled `.jar` files from our GH release, if we were to publish it.

2023-09-06 08:25 UTC, Johannes-Schneider commented on .github/workflows/prepare_release.yml
> +          mvn $MVN_CLI_ARGS install jacoco:report org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy -DaltReleaseDeploymentRepository=local::file:./rel-${{ needs.prepare-release.outputs.releas
But if you'd like to handle those concerns as part of the other BLI, I'm fine with that.

2023-09-06 08:26 UTC, KevinHudemann commented on .github/workflows/prepare_release.yml
> +          mvn $MVN_CLI_ARGS install jacoco:report org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy -DaltReleaseDeploymentRepository=local::file:./rel-${{ needs.prepare-release.outputs.releas
Yes we already picked the other BLI up so I think its ok to handle it with a follow-up.

2023-09-06 08:27 UTC, KevinHudemann commented on .github/workflows/prepare_release.yml
> +    needs: [archetypes, codeql, prepare-release]
Sure will do.

2023-09-06 08:29 UTC, Johannes-Schneider commented on .github/workflows/prepare_release.yml
> +          mvn $MVN_CLI_ARGS install jacoco:report org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy -DaltReleaseDeploymentRepository=local::file:./rel-${{ needs.prepare-release.outputs.releas
Do we also handle the inclusion of BlackDuck and Fosstar as part of an other ticket?

2023-09-06 08:30 UTC, stippi2 commented on .github/workflows/prepare_release.yml
> +          mvn $MVN_CLI_ARGS install jacoco:report org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy -DaltReleaseDeploymentRepository=local::file:./rel-${{ needs.prepare-release.outputs.releas
My guess is that the deploy target needs to be called in a separate mvn invokation using excludes that are generated just like for the snapshot release.

2023-09-06 08:30 UTC, KevinHudemann commented on .github/workflows/prepare_release.yml
> +          mvn $MVN_CLI_ARGS install jacoco:report org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy -DaltReleaseDeploymentRepository=local::file:./rel-${{ needs.prepare-release.outputs.releas
Nope I'd include it in this PR. Already on it.

2023-09-06 12:36 UTC, Johannes-Schneider reviewed
Generally LGTM - just uncomment the commented blocks (maybe?)

2023-09-06 12:36 UTC, Johannes-Schneider commented on .github/workflows/prepare_release.yml
> +        #   ref: 'main'
This should be uncommented before merging this PR, right?

```suggestion
        with:
          ref: 'main'
```

2023-09-06 12:36 UTC, Johannes-Schneider commented on .github/workflows/prepare_release.yml
> +      #          key: maven-central
Is this supposed to be uncommented before merging as well?

2023-09-06 12:44 UTC, KevinHudemann commented on .github/workflows/prepare_release.yml
> +      #          key: maven-central
This cannot be uncommented as the verify of the archetypes doesn't work yet, since not all modules are part of this repo yet.
Thats why we hardcoded the sdk version in the archetypes for now to 4.20.

2023-09-06 12:45 UTC, Johannes-Schneider approved these changes

2023-09-06 13:03 UTC, merged