fix: OData Batch Error Handling
SAP/cloud-sdk-java pull request #543
Opened 2024-08-15 15:53 UTC by MatKuhr

## Context

Fix for #542 

## Definition of Done

- [x] Functionality scope stated & covered
- [ ] Tests cover the scope above
- [x] ~Error handling created / updated & covered by the tests above~
- [x] ~Documentation updated~
- [ ] Release notes updated

2024-08-15 16:14 UTC, MatKuhr commented on datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestGeneric.java
> +    final Map<String, Collection<String>> headers = new TreeMap<>();
driveby: improve test reliability by retaining the order

2024-08-15 21:02 UTC, MatKuhr commented on datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataRequestGeneric.java
> +    final Map<String, Collection<String>> headers = new TreeMap<>();
somehow doesn't fix the order being different on my machine. Reverting..

2024-08-16 05:40 UTC, CharlesDuboisSAP requested changes

2024-08-16 05:40 UTC, CharlesDuboisSAP commented on datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataHealthyResponseValidator.java
>              throw new ODataServiceErrorException(request, httpResponse, msgError, null, odataError.get());
This exception will be changed by the `request` assignment above.
Wouldn't it be better if the prepared exception was moved down line 64 to when it's thrown?

2024-08-16 05:40 UTC, CharlesDuboisSAP commented on datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/referenceservice/ODataClientBatchResponseParsingUnitTest.java
>              .isThrownBy(() -> batchResponse.getResult(create1))
That doesn't look right

2024-08-16 06:40 UTC, MatKuhr commented on datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/referenceservice/ODataClientBatchResponseParsingUnitTest.java
>              .isThrownBy(() -> batchResponse.getResult(create1))
why not?

2024-08-16 06:52 UTC, CharlesDuboisSAP commented on datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/referenceservice/ODataClientBatchResponseParsingUnitTest.java
>              .isThrownBy(() -> batchResponse.getResult(create1))
Behaviour change

2024-08-16 13:22 UTC, MatKuhr commented on datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/referenceservice/ODataClientBatchResponseParsingUnitTest.java
>              .isThrownBy(() -> batchResponse.getResult(create1))
Yes, but that is an intended (and I think non-breaking, because `ODataServiceErrorException` is a subclass of `ODataResponseException`) behaviour change 😉

2024-08-19 08:40 UTC, newtork commented on release_notes.md
> +- Improve the error handling for batch requests.
```suggestion
- Improve the error handling for OData batch requests.
```

2024-08-19 08:52 UTC, newtork commented on datamodel/odata-v4/odata-v4-core/src/test/java/com/sap/cloud/sdk/datamodel/odatav4/referenceservice/ODataClientBatchResponseParsingUnitTest.java
>              .isThrownBy(() -> batchResponse.getResult(create1))
It surprises me this exceptions is changing here. The if condition change only applied for requests of type `ODataRequestBatch`. This doesn't fit the `create1` variable. Debugging.

2024-08-19 09:27 UTC, newtork commented on datamodel/odata-client/src/main/java/com/sap/cloud/sdk/datamodel/odata/client/request/ODataHealthyResponseValidator.java
> +        ODataRequestGeneric request = result.getODataRequest();
(Comment)

I would prefer if this variable was called `origin` or `originRequest`, hoping next time I will understand `getODataRequest()` and `getHttpResponse()` are not directly connected!

2024-08-19 09:37 UTC, newtork submitted a review, later dismissed

2024-08-20 08:26 UTC, newtork approved these changes

2024-08-20 08:48 UTC, merged