Deploy snapshots to Maven central
SAP/cloud-sdk-java pull request #94
Opened 2023-10-17 08:21 UTC by KevinHudemann

2023-10-17 16:38 UTC, stippi2 commented on .github/workflows/deploy_snapshot.yaml
> +        required: false
I think there are parameter types which would result in different UI (not sure, but it should result in a checkmark). See here: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#defining-inputs-for-manually-triggered-workflows

2023-10-18 06:53 UTC, KevinHudemann commented on .github/workflows/deploy_snapshot.yaml
> +        required: false
Good point I'll try it out. Also didn't see the `choice` type before. I just read in an issue that there were problems with boolean inputs in the if conditions, which is why I opted for string but I'll quickly try it out. 👍

2023-10-18 06:54 UTC, stippi2 commented on .github/workflows/deploy_snapshot.yaml
> +        required: false
I also stumbled across that when trying to find a reference. But I think that's for (reusable) Actions, not Workflows.

2023-10-18 07:09 UTC, KevinHudemann commented on .github/workflows/deploy_snapshot.yaml
> +        required: false
Switched to boolean input type, now it looks like this:
![image](https://github.com/SAP/cloud-sdk-java/assets/61827895/e9116056-b5a3-4e53-a0df-b213482f69b7)

2023-10-18 07:11 UTC, stippi2 submitted a review, later dismissed

2023-10-18 07:59 UTC, CharlesDuboisSAP reviewed
The notify-job never ran.
Also could you add the tech debt to this item: [[Pipeline] Remove GitHub workflows code duplication](https://github.com/SAP/cloud-sdk-java-backlog/issues/318#top)

2023-10-18 08:03 UTC, KevinHudemann commented
> The notify-job never ran. Also could you add the tech debt to this item: [[Pipeline] Remove GitHub workflows code duplication](https://github.com/SAP/cloud-sdk-java-backlog/issues/318#top)

Good catch! The notify job was missing the `scan` job in the `needs` property. In general, the notify job only runs if there was a failure.

2023-10-18 08:51 UTC, stippi2 requested changes

2023-10-18 08:51 UTC, stippi2 commented on .github/workflows/deploy_snapshot.yaml
> +          ref: ${{ needs.prepare-release.outputs.branch_name }}
I would say this cannot work.

2023-10-18 09:05 UTC, KevinHudemann commented on .github/workflows/deploy_snapshot.yaml
> +          ref: ${{ needs.prepare-release.outputs.branch_name }}
Good catch. It worked actually, but I guess only because there is a reasonable fallback. I'll delete the ref

2023-10-18 09:07 UTC, stippi2 submitted a review, later dismissed
👍

2023-10-18 09:10 UTC, stippi2 approved these changes

2023-10-18 11:38 UTC, merged